mendix/native-widgets

.github/workflows/Build.yml, .github/workflows/NativeAutomatedTestsAndroid.yml, .github/workflows/Release.yml, .github/workflows/UnitTests.yml, scripts/release/module-automation/commons.js
Change base branch for native-widgets from master to main in the automation
=> fix: automation

packages/jsActions/mobile-resources-native/CHANGELOG.md, packages/jsActions/mobile-resources-native/package.json, packages/pluggableWidgets/bottom-sheet-native/CHANGELOG.md, packages/pluggableWidgets/bottom-sheet-native/package.json, packages/pluggableWidgets/bottom-sheet-native/src/package.xml, packages/pluggableWidgets/gallery-native/CHANGELOG.md, packages/pluggableWidgets/gallery-native/package.json, packages/pluggableWidgets/gallery-native/src/package.xml, packages/pluggableWidgets/intro-screen-native/CHANGELOG.md, packages/pluggableWidgets/intro-screen-native/package.json, packages/pluggableWidgets/intro-screen-native/src/package.xml, yarn.lock
-   Contains unit tests  ❌
-   Contains breaking changes ❌
-   Compatible with: MX 8️⃣, 9️⃣
-   Did you update version and changelog? ✅ 
-   PR title properly formatted (`[XX-000]: description`)? ✅ 
-   Works in Android ✅ 
-   [X] Bug fix
**react-native-device-info** package was updated to **8.7.1** fix **getDeviceName** function's problem. 
**getDeviceName** function should get the latest device name, not the factory name.
=> [MOO-1014] react-native-device-info package is updated to 8.7.1.

scripts/release/module-automation/commons.js
=> Fix module automation

packages/pluggableWidgets/bar-chart-native/package.json
=> fix(bar-chart-native): bump package.json version

.github/workflows/Build.yml, .github/workflows/Release.yml, configs/jsactions/rollup-plugin-collect-dependencies.js, configs/jsactions/rollup.config.js
In this pull request, we've made several updates to our GitHub Actions workflows. Key changes include:
**Updated Action Packages:** We've upgraded some of the action packages we use in our workflows to ensure better performance and compatibility with our current setup.
**Optimized Yarn Caching:** We've removed an unnecessary section that was previously used for Yarn's cache handling. 
**Disabled Actions on Windows:** We've decided to disable the running of actions on Windows environments. This decision was made to focus our resources and testing efforts more effectively on our primary development environments.
=> Fix pipeline

packages/jsActions/nanoflow-actions-native/CHANGELOG.md, packages/jsActions/nanoflow-actions-native/src/other/Base64Encode.ts
=> [MOO-1123]: module nanoflow commons cw 9503 warning 9.24

packages/jsActions/nanoflow-actions-native/package.json
=> fix(nanoflow-actions-native): update minimum mx version

packages/jsActions/mobile-resources-native/CHANGELOG.md, packages/jsActions/mobile-resources-native/src/file-download/DownloadFile.ts, packages/jsActions/mobile-resources-native/typings/mx.d.ts
=> Backport [MOO-1317] Fix file download jsAction - read the files unencrypted to 9.24

packages/jsActions/mobile-resources-native/CHANGELOG.md, packages/jsActions/mobile-resources-native/src/file-download/DownloadFile.ts, packages/jsActions/mobile-resources-native/typings/mx.d.ts
-   Contains unit tests  ❌
-   Contains breaking changes  ❌
-   Did you update version and changelog? ✅ 
-   PR title properly formatted (`[XX-000]: description`)? ✅ 
-   Works in Android ✅ 
-   Works in iOS ✅ 
-   Works in Tablet ✅ 
-   [x] Bug fix
_..._
_..._
=> [MOO-1317] Fix file download jsAction - read the files unencrypted

packages/jsActions/mobile-resources-native/src/file-download/DownloadFile.ts
=> [MOO-1317]: add downloaded file encryption fix backward compatibility backport 9.24

packages/jsActions/mobile-resources-native/src/file-download/DownloadFile.ts
-   Contains unit tests ❌
-   Contains breaking changes  ❌
-   Did you update version and changelog? ❌
-   Works in Android ✅ 
-   Works in iOS ✅ 
-   Works in Tablet ✅ 
-   [x] Bug fix
_We have recently introduced a fix to download file jsAction if file encryption is enabled. this PR is to make sure these changes doesn't affect the older studio pro versions that don't expose readFileBlob functionality_
_..._
_Please add extra …
=> [MOO-1317]: add downloaded file encryption fix backward compatibility

configs/jsactions/rollup.config.js, package.json, packages/jsActions/mobile-resources-native/CHANGELOG.md, patches/@mendix+pluggable-widgets-tools+9.24.0.patch, yarn.lock
-   Contains unit tests ❌
-   Contains breaking changes ❌
_..._
_..._
=> Rename react navigation in rollup

.github/workflows/Build.yml, .github/workflows/Release.yml, .github/workflows/UnitTests.yml, packages/jsActions/mobile-resources-native/CHANGELOG.md, packages/jsActions/mobile-resources-native/src/notifications/RequestNotificationPermission.ts
-   Contains unit tests ❌
-   Contains breaking changes  ❌
-   Did you update version and changelog? ✅ 
_..._
_..._
=> [MOO-1519]: fix request notification permission return value

packages/pluggableWidgets/video-player-native/CHANGELOG.md, packages/pluggableWidgets/video-player-native/package.json, packages/pluggableWidgets/video-player-native/src/VideoPlayer.tsx, packages/pluggableWidgets/video-player-native/src/__tests__/VideoPlayer.spec.tsx, packages/pluggableWidgets/video-player-native/src/package.xml, yarn.lock
Reverts mendix/native-widgets#170
=> Revert "[MOO-803]: react-native-video dependency upgraded (10.12)"

packages/jsActions/mobile-resources-native/CHANGELOG.md, packages/jsActions/mobile-resources-native/package.json, packages/pluggableWidgets/progress-circle-native/CHANGELOG.md
-   Compatible with: MX 8, 9, 10
_..._
_..._
=> chore(mobile-resources-native): update changelogs

.github/actions/slack-notification/action.yml, .github/workflows/MarketplaceRelease.yml, .github/workflows/UpdateMinimumMxVersion.yml
-   Compatible with: MX 8, 9, 10
_..._
_..._
=> [MOO-1834]: Add workflow to update minimumMXVersion

packages/pluggableWidgets/safe-area-view-native/CHANGELOG.md, packages/pluggableWidgets/safe-area-view-native/package.json, packages/pluggableWidgets/safe-area-view-native/src/SafeAreaView.tsx, packages/pluggableWidgets/safe-area-view-native/src/package.xml, yarn.lock
-   [X] Bug fix
Fixing the Safe Area View on Samsung Devices.
=> fix: fix safe area overlapping issue with navigation bar

packages/jsActions/nanoflow-actions-native/CHANGELOG.md, packages/jsActions/nanoflow-actions-native/src/geolocation/RequestLocationPermission.ts
=> fix: [MOO-2022] location permission issue on iOS

.github/workflows/MarketplaceRelease.yml
- Resolve pipeline configuration issues
- Add comprehensive error handling
- Enhance logging mechanism for better debugging
- Improve error reporting and diagnostics
=> [Fix] Native widgets pipeline

packages/jsActions/nanoflow-actions-native/package.json
Reverts mendix/native-widgets#332
=> Revert "chore: bump nanoflow-commons"
